#------------------------------------------------------------------------#

version: "3.7"

services: 

#---SPA------------------------------------------------------------------#

    1_spa:
        container_name  : todoapp_spa
        image           : hy2015tr/todoapp_spa
        build           : ./TodoSPA/.
        ports           : [8080:4200]
        depends_on      : [2_api]

#---API------------------------------------------------------------------#

    2_api: 
        container_name  : todoapp_api
        image           : hy2015tr/todoapp_api
        build           : ./TodoAPI/.
        ports           : [5200:5000]
        depends_on      : [3_dat]

#---DAT------------------------------------------------------------------#

    3_dat: 
        container_name  : todoapp_dat
        image           : hy2015tr/todoapp_dat
        build           : ./TodoDAT/.
        ports           : [1435:1433]
        volumes         : [./TodoDAT/.:/var/opt/mssql/data:rw]

#------------------------------------------------------------------------#